# .github/workflows/deploy.yml

name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering from the Actions tab

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # 1. Checkout the Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Setup Node.js Environment
      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Ensure this matches your project's Node.js version

      # 3. Install Dependencies and Build the Project
      - name: Build the Project
        run: |
          make
        # If 'make' already handles cd-ing into 'lalolens', adjust accordingly

      # 4. Create .nojekyll File in the 'www' Directory
      - name: Create .nojekyll File
        run: touch www/.nojekyll

      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # Adjust this path to your build output directory
