# .github/workflows/deploy.yml

name: Deploy to GitHub Pages

on:
  # Trigger the workflow on push to the main branch
  push:
    branches:
      - main

  # Allow manual triggering of the workflow from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # 1. Checkout the Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Setup Node.js Environment
      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version your project requires

      # 3. Install Dependencies and Build the Project
      - name: Build the Project
        run: |
          make
        # If your Makefile already handles changing directories, adjust accordingly

      # 4. Create .nojekyll File in the 'www' Directory
      - name: Create .nojekyll File
        run: touch www/.nojekyll

      # 5. Upload Pages Artifact
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: www  # Ensure this path points to your build output directory

      # 6. Deploy to GitHub Pages (Only on Push Events)
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'  # Ensures deployment only happens on push, not on manual runs
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Use your PAT if necessary
